export const JobsList = [
  {
    _id: "ddfgsb5435345gs",
    SchoolName: "The English School",
    jobTitle: "ESL Teacher",
    location: "Daejeon, South Korea",
    schoolDescription:
      "We are school that loves k_ids and we want them to learn. We have high standards.",
    salary: "3m won a month",
    jobDescription: "You will be responsible for teaching English to children.",
    requirements: "TEFL, degree, clean criminal record check",
    otherBenefits: "Free return air ticket if you stay for the full year.",
    contactEmail: "ESLSchool@school.com",
    website: "",
    dateCreated: "2025-01-15T14:30:00Z",
  },
  {
    _id: "a872jh27gs62",
    SchoolName: "Maple Grove Language Academy",
    jobTitle: "ESL Instructor",
    location: "Busan, South Korea",
    schoolDescription:
      "A m_id-sized academy focused on communicative English for elementary students.",
    salary: "2.6m won a month",
    jobDescription:
      "Teach 25 hours per week using our textbook-based curriculum. Small classes.",
    requirements: "BA degree, native speaker, 100-hour TEFL",
    otherBenefits: "Housing prov_ided, health insurance, severance",
    contactEmail: "hr@maplegrovekr.com",
    website: "",
    dateCreated: "2025-02-01T10:00:00Z",
  },
  {
    _id: "djw72hd8fsa1",
    SchoolName: "Global Br_idge Institute",
    jobTitle: "Conversational English Teacher",
    location: "Seoul, South Korea",
    schoolDescription:
      "A well-established private academy known for adult conversation classes.",
    salary: "2.8m won a month",
    jobDescription:
      "Lead conversation-focused classes for adult learners. Curriculum prov_ided.",
    requirements: "Bachelor's degree, TEFL preferred, positive attitude",
    otherBenefits: "Performance bonuses, pa_id vacation, pension",
    contactEmail: "jobs@gbiedu.net",
    website: "",
    dateCreated: "2025-02-10T13:45:00Z",
  },
  {
    _id: "f92hd72nka88",
    SchoolName: "Sunrise International Kindergarten",
    jobTitle: "Kindergarten English Teacher",
    location: "Daegu, South Korea",
    schoolDescription:
      "A progressive kindergarten focused on creativity, music, and language immersion.",
    salary: "2.5m won a month",
    jobDescription:
      "Teach English through play-based activities, songs, and storytelling.",
    requirements: "Degree in education or related field preferred",
    otherBenefits: "Prov_ided lunch, pa_id training, full benefits",
    contactEmail: "apply@sunriseik.kr",
    website: "",
    dateCreated: "2025-03-05T09:15:00Z",
  },
  {
    _id: "72gs8kk92jdh",
    SchoolName: "Blue Horizon English Center",
    jobTitle: "Elementary ESL Teacher",
    location: "Gwangju, South Korea",
    schoolDescription:
      "Small family-run hagwon with supportive staff and well-organized curriculum.",
    salary: "2.4m won a month",
    jobDescription:
      "Teach elementary students reading, writing, and speaking using structured lessons.",
    requirements: "Native speaker, TEFL, stable work history",
    otherBenefits: "One-way airfare, furnished housing, medical insurance",
    contactEmail: "bluehorizon@korea.com",
    website: "",
    dateCreated: "2025-01-28T08:20:00Z",
  },
  {
    _id: "q71hdd91nq09",
    SchoolName: "Korea Polytechnic University",
    jobTitle: "University Conversation Instructor",
    location: "Incheon, South Korea",
    schoolDescription:
      "A respected technical university offering English electives for students.",
    salary: "2.7m won a month + vacation",
    jobDescription:
      "Teach conversation courses to university students. Low teaching hours.",
    requirements: "Master's degree in any field, experience preferred",
    otherBenefits: "4 months pa_id vacation, office prov_ided, pension",
    contactEmail: "hiring@kpu.ac.kr",
    website: "",
    dateCreated: "2025-02-18T16:40:00Z",
  },
  {
    _id: "sa81k3ls91hd",
    SchoolName: "Happy Minds Learning Center",
    jobTitle: "Afterschool English Teacher",
    location: "Suwon, South Korea",
    schoolDescription:
      "Small after-school program located ins_ide a public elementary school.",
    salary: "2.3m won a month",
    jobDescription:
      "Teach English to grades 1–4 using project-based materials.",
    requirements: "Any bachelor’s degree, TEFL, criminal record check",
    otherBenefits: "Pa_id hol_idays, pension, curriculum included",
    contactEmail: "apply@happyminds.co.kr",
    website: "",
    dateCreated: "2025-02-03T12:10:00Z",
  },
  {
    _id: "n63js92hgd72",
    SchoolName: "Eden English Academy",
    jobTitle: "M_iddle School English Teacher",
    location: "Ulsan, South Korea",
    schoolDescription:
      "A modern hagwon specializing in academic writing and debate.",
    salary: "3.0m won a month",
    jobDescription:
      "Teach writing, grammar, and reading comprehension to motivated students.",
    requirements: "English major preferred, TEFL, strong writing skills",
    otherBenefits: "Housing allowance, annual bonus",
    contactEmail: "eden@ulsanacademy.kr",
    website: "",
    dateCreated: "2025-01-25T11:22:00Z",
  },
  {
    _id: "kk12ms77fsa7",
    SchoolName: "Little Steps Kindergarten",
    jobTitle: "Kindergarten Homeroom Teacher",
    location: "Jeju Island, South Korea",
    schoolDescription:
      "A warm, family-oriented kindergarten with a nature-focused curriculum.",
    salary: "2.8m won a month",
    jobDescription:
      "Lead a kindergarten class with English immersion activities.",
    requirements: "Degree + TEFL, experience with young learners",
    otherBenefits: "Rent support, lunch, island allowance",
    contactEmail: "hello@littlestepsjeju.kr",
    website: "",
    dateCreated: "2025-03-10T14:05:00Z",
  },
  {
    _id: "j29bd18skq22",
    SchoolName: "Bright Future English Academy",
    jobTitle: "Evening English Teacher",
    location: "Seoul (Gangnam), South Korea",
    schoolDescription:
      "Premium English academy offering advanced reading and critical thinking classes.",
    salary: "3.5m won a month",
    jobDescription:
      "Teach advanced students academic reading and structured writing.",
    requirements: "English/linguistics degree preferred",
    otherBenefits: "Tuition support, high housing stipend",
    contactEmail: "careers@brightfuturegangnam.com",
    website: "",
    dateCreated: "2025-03-08T17:40:00Z",
  },
  {
    _id: "19sas82mmk77",
    SchoolName: "Oxford English Village",
    jobTitle: "Immersion Teacher",
    location: "Chuncheon, South Korea",
    schoolDescription:
      "A rural English village where students practice real-life language immersion.",
    salary: "2.7m won a month",
    jobDescription:
      "Teach themed lessons in simulated environments (airport, café, shops).",
    requirements: "BA degree, TEFL, enthusiasm for drama/roleplay",
    otherBenefits: "Prov_ided housing, meals, beautiful location",
    contactEmail: "oxfordvillage@chuncheon.go.kr",
    website: "",
    dateCreated: "2025-02-22T09:50:00Z",
  },
  {
    _id: "p28snd91jss1",
    SchoolName: "Skyline International School",
    jobTitle: "Primary English Teacher",
    location: "Pyeongtaek, South Korea",
    schoolDescription:
      "International school serving families connected to overseas business and military.",
    salary: "3.2m won a month",
    jobDescription:
      "Teach primary-level English and support homeroom activities.",
    requirements: "Education degree, teaching license preferred",
    otherBenefits: "Tuition discount for children, professional development",
    contactEmail: "recruit@skylineis.kr",
    website: "",
    dateCreated: "2025-03-02T13:25:00Z",
  },
  {
    _id: "ll82jsk03fhs",
    SchoolName: "Tomorrow English Institute",
    jobTitle: "Speaking & Listening Teacher",
    location: "Daejeon, South Korea",
    schoolDescription:
      "A friendly academy focused on speaking fluency for teens.",
    salary: "2.6m won a month",
    jobDescription:
      "Teach speaking classes using roleplays, dialogues, and group activities.",
    requirements: "Bachelor’s degree, clear accent, TEFL preferred",
    otherBenefits: "Pa_id training, collaborative staff",
    contactEmail: "jobs@tomorrowenglish.kr",
    website: "",
    dateCreated: "2025-01-31T15:00:00Z",
  },
  {
    _id: "ud77m20bsq92",
    SchoolName: "Pinehill English Academy",
    jobTitle: "After-School English Teacher",
    location: "Gimhae, South Korea",
    schoolDescription:
      "After-school English center partnered with several local elementary schools.",
    salary: "2.4m won a month",
    jobDescription:
      "Teach fun and engaging lessons to grades 1–5 using our structured books.",
    requirements: "BA degree, TEFL, reliable and friendly",
    otherBenefits: "Pa_id vacation days, split shift allowance",
    contactEmail: "pinehill@education.kr",
    website: "",
    dateCreated: "2025-02-12T10:55:00Z",
  },
  {
    _id: "aa92jdd28k09",
    SchoolName: "Elite English Prep",
    jobTitle: "Test Prep English Instructor",
    location: "Seoul, South Korea",
    schoolDescription:
      "Top-tier academy specializing in TOEFL, IELTS, and SAT prep.",
    salary: "3.8m won a month",
    jobDescription:
      "Teach test strategies, reading comprehension, and writing for exams.",
    requirements: "High English proficiency, experience teaching test prep",
    otherBenefits: "Performance bonuses, robust training program",
    contactEmail: "eliteprep@seouledu.org",
    website: "",
    dateCreated: "2025-03-12T18:10:00Z",
  },
  {
    _id: "m18js91kdl22",
    SchoolName: "Harmony English Center",
    jobTitle: "Part-Time ESL Teacher",
    location: "Gwangju, South Korea",
    schoolDescription:
      "Relaxed, community-focused center offering evening English programs.",
    salary: "1.4m won a month (part-time)",
    jobDescription:
      "Teach 3 hours per day, four days a week. Light curriculum.",
    requirements: "Native speaker, friendly personality",
    otherBenefits: "Flexible schedule, supportive manager",
    contactEmail: "hello@harmonyec.kr",
    website: "",
    dateCreated: "2025-03-15T08:30:00Z",
  },
];
